Replace build and config with current used version, add ability to mo…
intermedia-net/pjproject-android-builder pull request #1
Opened 2023-03-03 12:18 UTC by inekrasov-intermedia

Replace build and config with current used version, add ability to mount input and output

2023-03-06 08:23 UTC, anikitin-intermedia requested changes

2023-03-06 08:23 UTC, anikitin-intermedia commented on config.conf
> +BCG729_VERSION=master
Why master? I think it is better to use specific version

2023-03-06 08:23 UTC, anikitin-intermedia commented on config.conf
> +SKIP_OPENH264_DEMO=0
Why we need this demo?

2023-03-06 10:19 UTC, inekrasov-intermedia commented on config.conf
> +BCG729_VERSION=master
I used our local version and it contains master version. But maybe it was my mistake, can you check it?

2023-03-06 10:20 UTC, inekrasov-intermedia commented on config.conf
> +SKIP_OPENH264_DEMO=0
It's the same, but yes, we can disable it, I think.

2023-03-09 08:30 UTC, anikitin-intermedia commented on config.conf
> +BCG729_VERSION=master
Ok, got it!

2023-03-09 08:31 UTC, anikitin-intermedia commented on config.conf
> +SKIP_OPENH264_DEMO=0
No, I don't see this flag in my config.conf file at all

2023-03-13 09:49 UTC, inekrasov-intermedia commented on config.conf
> +SKIP_OPENH264_DEMO=0
Fixed and returned to 1 (skip)

2023-03-13 10:04 UTC, anikitin-intermedia approved these changes

2023-03-13 10:36 UTC, dshamaev-intermedia approved these changes

2023-03-13 10:57 UTC, merged